[phases.setup]
nixPkgs = ["ffmpeg", "python311Full", "libsndfile", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["python3.11 -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python sorcerer.py daemon"
